### ISSUE TITLE
require js optimizer integration?

### ISSUE THREAD

**Issue by propertunist** [mrclay/Elgg-mrclay_combiner#3]
i just found this part of requireJS that appears to be the missing link for file optimisation in elgg.. did you consider this as an option? http://www.requirejs.org/docs/optimization.html

**Comment by mrclay** [comment]
Let's open this on Elgg/Elgg. The problem is r.js requires all resources to be static files. We'd need some kind of pre-rendering into /cache and (I worry) other changes to the bootstrap we can't do. Would be nice to have someone working toward that though.
